[package]
name = "adventofcode-rust-2015"
version = "0.0.0"
edition = "2018"

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
#regex = "*"
#lazy_static = "*"
itertools = "*"
rust-crypto = "*"
unicode-segmentation = "*"