[package]
name = "adventofcode-rust-2015"
version = "0.0.0"
edition = "2021"

[profile.bench]
debug = true

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"

anyhow = "*"
itertools = "*" # day 03
rust-crypto = "*" # day 04
unicode-segmentation = "*" # day 05
nom = "*" # day 07, 08